# Font
font_family Jetbrains Mono Nerd Font
font_size 14

# Colors

include themes/catppuccin/macchiato.conf
background_opacity 0.8

# Tab bar
tab_bar_edge                top
tab_bar_style               powerline
tab_title_template          {' '}{title}{' ({})'.format(num_windows) if num_windows > 1 else ''}{' '}

# New tab/window in same directoty
map kitty_mod+enter launch --cwd=current
map kitty_mod+t     new_tab_with_cwd

# Window
remember_window_size no
initial_window_width  1000
initial_window_height 600


# Windows arrange (layouts)
enabled_layouts tall:bias=50;full_size=1;mirrored=false,grid,horizontal,vertical

# reset all windows in the tab to default sizes
map ctrl+home resize_window reset
map ctrl+alt+u kitten unicode_input

# linux_display_server x11
hide_window_decorations titlebar-only
strip_ansi_escape_codes yes
repaint_delay 10

# No audio bell
enable_audio_bell no

# Sync monitor FPS with kitty
sync_to_monitor yes

# Block cursor no blink
shell_integration no-cursor
cursor_blink_interval 0

# Default editor
editor nvim
