CompileFlags:
  Add:
    [
      -Wall,
      -Wextra,
      -Wpedantic,
      -isystem/usr/include/c++/14,
      -isystem/usr/include/c++/14/x86_64-alt-linux,
      -isystem/usr/include/c++/14/backward,
      -isystem/usr/lib64/gcc/x86_64-alt-linux/14/include,
      -isystem/usr/local/include,
      -isystem/usr/include,
    ]
---
If:
  PathExclude: [.*\.c]
CompileFlags:
  Add: [-std=c++23]

---
If:
  PathMatch: .*\.c$
CompileFlags:
  Add: [-std=c23]
