exec-once = hyprpaper
exec-once = PATH=$PATH:/usr/sbin ashell
exec-once = copyq --start-server
exec-once = ~/.config/hypr/portals.sh
exec-once = /usr/libexec/polkit-1/polkit-gnome-authentication-agent-1
