# https://wiki.hypr.land/Configuring/
##############
### COLORS ###
##############

source = ~/.config/hypr/hyprland/macchiato.conf

################
### MONITORS ###
################

monitor=,preferred,auto,1

###################
### MY PROGRAMS ###
###################

source = ~/.config/hypr/hyprland/my_programs.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/hyprland/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/hyprland/env.conf

###################
### PERMISSIONS ###
###################

source = ~/.config/hypr/hyprland/permissions.conf

#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/hyprland/look.conf

#############
### INPUT ###
#############

source = ~/.config/hypr/hyprland/input.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/hyprland/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/hyprland/windowrules.conf
